# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='title0',
            field=models.CharField(default='title', max_length=32),
        ),
    ]
