# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170307_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title0',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
